version: '3.3'

services:
  backend:
    container_name: app-drone-feeder
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file: ./src/main/resources/secrets.properties
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: drone_feeder_db
    depends_on:
      - mysql
  # Database
  mysql:
    image: mysql
    volumes:
      # Define um volume interno do Docker para persistir os dados
      - my-db:/var/lib/mysql
      - ./init-mysql.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  # Cria o volume interno do Docker
  my-db: